export const users = [
    {
        _id: "u1",
        name: "Rohan Verma",
        email: "rohan@suge.app",
        role: "freelancer",
        createdAt: Date.now(),
    },
];

export const clients = [
    {
        _id: "c1",
        userId: "u1",
        name: "Anita Sharma",
        email: "anita@startupco.com",
        company: "Startup Co.",
        phone: "9876543210",
        address: "Mumbai, India",
        linkedUserId: null,
        createdAt: Date.now(),
    },
    {
        _id: "c2",
        userId: "u1",
        name: "David Miller",
        email: "david@designhub.io",
        company: "DesignHub",
        phone: "+1 234 567 890",
        address: "New York, USA",
        linkedUserId: null,
        createdAt: Date.now(),
    },
];

export const invoices = [
    {
        _id: "inv1",
        userId: "u1",
        clientId: "c1",
        title: "Website Redesign – Jan 2025",
        totalAmount: 35000,
        currency: "INR",
        status: "paid",
        issuedOn: "2025-01-05",
        dueOn: "2025-01-20",
        createdAt: Date.now(),
    },
    {
        _id: "inv2",
        userId: "u1",
        clientId: "c2",
        title: "Logo + Brand Kit – Feb 2025",
        totalAmount: 1200,
        currency: "USD",
        status: "sent",
        issuedOn: "2025-02-02",
        dueOn: "2025-02-15",
        createdAt: Date.now(),
    },
];

export const payments = [
    {
        _id: "pay_1",
        userId: "user_123",
        invoiceId: "inv_1",
        clientId: "client_1",
        title: "Website Design Payment",
        amount: 25000,
        currency: "INR",
        paymentMethod: "UPI",
        status: "paid",
        date: "2025-01-05",
        notes: "Final payment for landing page design",
    },
    {
        _id: "pay_2",
        userId: "user_123",
        invoiceId: "inv_2",
        clientId: "client_2",
        title: "E-commerce UI Project",
        amount: 40000,
        currency: "INR",
        paymentMethod: "Bank Transfer",
        status: "paid",
        date: "2025-01-12",
        notes: "Part 1 payment for full UI revamp",
    },
    {
        _id: "pay_3",
        userId: "user_123",
        invoiceId: "inv_3",
        clientId: "client_3",
        title: "Logo & Branding Package",
        amount: 12000,
        currency: "INR",
        paymentMethod: "PayPal",
        status: "paid",
        date: "2025-01-18",
        notes: "International client branding essentials",
    },
    {
        _id: "pay_4",
        userId: "user_123",
        invoiceId: "inv_4",
        clientId: "client_2",
        title: "Dashboard Development Milestone",
        amount: 30000,
        currency: "INR",
        paymentMethod: "UPI",
        status: "paid",
        date: "2025-01-22",
        notes: "Milestone 2 successfully delivered",
    },
    {
        _id: "pay_5",
        userId: "user_123",
        invoiceId: "inv_5",
        clientId: "client_1",
        title: "Monthly Maintenance Retainer - Jan",
        amount: 10000,
        currency: "INR",
        paymentMethod: "Bank Transfer",
        status: "paid",
        date: "2025-01-28",
        notes: "Routine website maintenance",
    },
    {
        _id: "pay_6",
        userId: "user_123",
        invoiceId: "inv_6",
        clientId: "client_4",
        title: "Portfolio Website Build",
        amount: 18000,
        currency: "INR",
        paymentMethod: "UPI",
        status: "paid",
        date: "2025-02-03",
        notes: "Delivered fully responsive web portfolio",
    },
    {
        _id: "pay_7",
        userId: "user_123",
        invoiceId: "inv_7",
        clientId: "client_5",
        title: "Social Media Graphics Pack",
        amount: 8000,
        currency: "INR",
        paymentMethod: "PayPal",
        status: "paid",
        date: "2025-02-07",
        notes: "Pack of Instagram posts + reel covers",
    },
    {
        _id: "pay_8",
        userId: "user_123",
        invoiceId: "inv_8",
        clientId: "client_3",
        title: "Brand Consultation Session",
        amount: 5000,
        currency: "INR",
        paymentMethod: "UPI",
        status: "paid",
        date: "2025-02-10",
        notes: "1-hour brand strategy call + follow-up",
    },
    {
        _id: "pay_9",
        userId: "user_123",
        invoiceId: "inv_9",
        clientId: "client_2",
        title: "Mobile App UI Kit Delivery",
        amount: 22000,
        currency: "INR",
        paymentMethod: "Bank Transfer",
        status: "paid",
        date: "2025-02-15",
        notes: "Completed Figma UI kit for iOS + Android",
    },
    {
        _id: "pay_10",
        userId: "user_123",
        invoiceId: "inv_10",
        clientId: "client_6",
        title: "Landing Page Redesign",
        amount: 15000,
        currency: "INR",
        paymentMethod: "UPI",
        status: "paid",
        date: "2025-02-19",
        notes: "Faster, SEO-friendly redesign",
    },
];
  
